/*
 *  Constantes.h
 *  FlyAway
 *
 *  Created by Maxime Britto on 20/04/10.
 *  Copyright 2010 Logimax SARL. All rights reserved.
 *
 */

#define LARGEUR_ECRAN 320
#define HAUTEUR_ECRAN 560

#define LARGEUR_HERO 50
#define HAUTEUR_HERO 50

#define LARGEUR_OBSTACLE 50
#define HAUTEUR_OBSTACLE 50

#define HAUTEUR_ARRIVEE 70

//A CODER PLUS TARD // VOIR MEME CREER CLASSE PARTIE ?
#define ADDED_OBSTACLE_POINT 75 // AJOUT DES POINTS AU JOUEUR A CHAQUE AJOUT D UN NOUVEL OBSTACLE
#define CRASH_COST 50 // ENLEVE DES POINT EN CAS DE COLLISION DU HERO AVEC UN OBSTACLE
#define MAX_LEVEL 20 // NIVEAU MAXI
